# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
kotlin = "2.2.21"
springBoot = "3.5.8"
springDependencyManagement = "1.1.7"
exposed = "1.0.0-rc-4"
jackson = "2.20.1"
postgresql = "42.7.8"
junit = "6.0.1"
druid = "1.2.24"
mybatisPlus = "3.5.5"
mysql = "9.1.0"
knife4j = "4.5.0"
springdoc = "2.8.9"
mapstruct = "1.6.3"
xxlJob = "3.2.0"
fastexcel = "1.3.0"
minio = "8.5.10"
aliyunSdkOss = "3.16.3"
redisson = "3.51.0"
velocity = "2.3"
ip2region = "2.7.0"
aliyunSdkCore = "4.7.6"
aliyunSdkDysmsapi = "2.2.1"
weixinJavaMiniApp = "4.7.7.B"
caffeine = "2.9.3"
hutool = "5.8.41"
lombokMapstructBinding = "0.2.0"
lombok = "1.18.42"
[libraries]
# Libraries can be bundled together for easier import
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
springBootConfigurationProcessor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springBoot" }
springBootDevtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springBoot" }
springBootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
springBootStarterDataJdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc", version.ref = "springBoot" }
springBootStarterDataRedis = { module = "org.springframework.boot:spring-boot-starter-data-redis", version.ref = "springBoot" }
springBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
springBootStarterCache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "springBoot" }
springBootStarterAop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "springBoot" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springBoot" }
springBootStarterWebsocket = { module = "org.springframework.boot:spring-boot-starter-websocket", version.ref = "springBoot" }
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
springBootStarterMail = { module = "org.springframework.boot:spring-boot-starter-mail", version.ref = "springBoot" }
exposedSpringBootStarter = { module = "org.jetbrains.exposed:exposed-spring-boot-starter", version.ref = "exposed" }
comAlibabaDruidSpringBootStarter = { module = "com.alibaba:druid-spring-boot-starter", version.ref = "druid" }
mybatisPlus = { module = "com.baomidou:mybatis-plus-spring-boot3-starter", version.ref = "mybatisPlus" }
jacksonModuleKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
kotlinTestJunit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

#接口文档
knife4j = { module = "com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter", version.ref = "knife4j" }
springdocOpenapiStarterWebmvcUi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
#对象映射
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
#定时任务
xxlJobCore = { module = "com.xuxueli:xxl-job-core", version.ref = "xxlJob" }
#Excel工具
fastexcel = { module = "cn.idev.excel:fastexcel", version.ref = "fastexcel" }
#对象存储
minio = { module = "io.minio:minio", version.ref = "minio" }
aliyunSdkOss = { module = "com.aliyun.oss:aliyun-sdk-oss", version.ref = "aliyunSdkOss" }
#分布式锁
redissonSpringBootStarter = { module = "org.redisson:redisson-spring-boot-starter", version.ref = "redisson" }
#代码生成器
mybatisPlusGenerator = { module = "com.baomidou:mybatis-plus-generator", version.ref = "mybatisPlus" }
velocityEngineCore = { module = "org.apache.velocity:velocity-engine-core", version.ref = "velocity" }
#org.lionsoul:ip2region
#IP地区转换
ip2region = { module = "org.lionsoul:ip2region", version.ref = "ip2region" }
#阿里云短信
aliyunJavaSdkCore = { module = "com.aliyun:aliyun-java-sdk-core", version.ref = "aliyunSdkCore" }
aliyunJavaSdkDysmsapi = { module = "com.aliyun:aliyun-java-sdk-dysmsapi", version.ref = "aliyunSdkDysmsapi" }
#微信SDK
weixinJavaMiniApp = { module = "com.github.binarywang:weixin-java-miniapp", version.ref = "weixinJavaMiniApp" }
#本地缓存
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

hutoolAll = { module = "cn.hutool:hutool-all", version.ref = "hutool" }
lombokMapstructBinding = { module = "org.projectlombok:lombok-mapstruct-binding", version.ref = "lombokMapstructBinding" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
[bundles]

admin = [
    "hutoolAll",
    "knife4j",
    "springdocOpenapiStarterWebmvcUi",
    "mapstruct",
    "xxlJobCore",
    "fastexcel",
    "minio",
    "aliyunSdkOss",
    "redissonSpringBootStarter",
    "mybatisPlusGenerator",
    "velocityEngineCore",
    "ip2region",
    "aliyunJavaSdkCore",
    "aliyunJavaSdkDysmsapi",
    "weixinJavaMiniApp",
    "caffeine",
    "springBootConfigurationProcessor",
    "springBootStarterActuator",
    "springBootStarterWeb",
    "springBootStarterCache",
    "springBootStarterAop",
    "springBootStarterValidation",
    "springBootStarterWebsocket",
    "springBootStarterMail",
    "springBootStarterSecurity",
    "comAlibabaDruidSpringBootStarter",
]

springBootStarter = [
    "springBootConfigurationProcessor",
    "springBootStarterActuator",
    "springBootStarterWeb",
    "jacksonModuleKotlin",
    "kotlinReflect",
]

mybatisData = [
    "mybatisPlus",
    "springBootStarterDataRedis",
]

exposedData = [
    "springBootStarterDataJdbc",
    "springBootStarterDataRedis",
    "exposedSpringBootStarter",
]

jdbcDriver = [
    "postgresql",
    "mysql"
]

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

